version: 2
jobs:
  build:
    docker:
      - image: docker:dind
    working_directory: /code
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t mber-rust .
      - deploy:
          name: Push application Docker image
          command: |
            echo $HUB_KEY | docker login -u $HUB_USERNAME --password-stdin
            docker tag mber-rust "${HUB_USERNAME}/mber-rust:${CIRCLE_BRANCH}"
            docker push "${HUB_USERNAME}/mber-rust:${CIRCLE_BRANCH}"
  test:
    docker:
      - image: docker:dind
    working_directory: ~/code
    steps:
      - setup_remote_docker
      - run: docker pull ${HUB_USERNAME}/mber-rust:${CIRCLE_BRANCH}
      - run: docker run -t -d --name="mber-rust" ${HUB_USERNAME}/mber-rust:${CIRCLE_BRANCH} /bin/bash
      - run: docker exec -it mber-rust cargo test -- --nocapture

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
